export const SUPPORTED_LANGUAGES = {
  python: {
    id: 'python',
    name: 'Python',
    version: '3.11',
    image: 'lightexec-python:3.11',
    extensions: ['.py'],
    compile: false,
    timeout: 10000,
    memory: 128,
  },
  javascript: {
    id: 'javascript',
    name: 'JavaScript (Node.js)',
    version: '20.x',
    image: 'lightexec-node:20',
    extensions: ['.js'],
    compile: false,
    timeout: 10000,
    memory: 128,
  },
  typescript: {
    id: 'typescript',
    name: 'TypeScript',
    version: '5.x',
    image: 'lightexec-node:20',
    extensions: ['.ts'],
    compile: true,
    timeout: 15000,
    memory: 256,
  },
  cpp: {
    id: 'cpp',
    name: 'C++',
    version: 'GCC 13',
    image: 'lightexec-cpp:gcc13',
    extensions: ['.cpp', '.cc'],
    compile: true,
    timeout: 20000,
    memory: 256,
  },
  java: {
    id: 'java',
    name: 'Java',
    version: '21',
    image: 'lightexec-java:21',
    extensions: ['.java'],
    compile: true,
    timeout: 20000,
    memory: 512,
  },
  rust: {
    id: 'rust',
    name: 'Rust',
    version: '1.75',
    image: 'lightexec-rust:1.75',
    extensions: ['.rs'],
    compile: true,
    timeout: 30000,
    memory: 512,
  },
  go: {
    id: 'go',
    name: 'Go',
    version: '1.21',
    image: 'lightexec-go:1.21',
    extensions: ['.go'],
    compile: true,
    timeout: 15000,
    memory: 256,
  },
  c: {
    id: 'c',
    name: 'C',
    version: 'GCC 13',
    image: 'lightexec-c:gcc13',
    extensions: ['.c'],
    compile: true,
    timeout: 20000,
    memory: 256,
  },
  ruby: {
    id: 'ruby',
    name: 'Ruby',
    version: '3.3',
    image: 'lightexec-ruby:3.3',
    extensions: ['.rb'],
    compile: false,
    timeout: 10000,
    memory: 128,
  },
  php: {
    id: 'php',
    name: 'PHP',
    version: '8.3',
    image: 'lightexec-php:8.3',
    extensions: ['.php'],
    compile: false,
    timeout: 10000,
    memory: 128,
  },
};

export const SECCOMP_PROFILE = {
  defaultAction: 'SCMP_ACT_ERRNO',
  architectures: ['SCMP_ARCH_X86_64', 'SCMP_ARCH_X86', 'SCMP_ARCH_X32'],
  syscalls: [
    { names: ['read', 'readv', 'pread64'], action: 'SCMP_ACT_ALLOW' },
    { names: ['write', 'writev', 'pwrite64'], action: 'SCMP_ACT_ALLOW' },
    { names: ['open', 'openat', 'close'], action: 'SCMP_ACT_ALLOW' },
    { names: ['mmap', 'munmap', 'mprotect'], action: 'SCMP_ACT_ALLOW' },
    { names: ['brk', 'sbrk'], action: 'SCMP_ACT_ALLOW' },
    { names: ['exit', 'exit_group'], action: 'SCMP_ACT_ALLOW' },
    { names: ['rt_sigaction', 'rt_sigreturn'], action: 'SCMP_ACT_ALLOW' },
    { names: ['stat', 'fstat', 'lstat'], action: 'SCMP_ACT_ALLOW' },
    { names: ['access', 'faccessat'], action: 'SCMP_ACT_ALLOW' },
    { names: ['getcwd', 'getpid', 'getuid', 'getgid'], action: 'SCMP_ACT_ALLOW' },
  ],
};

export const CONTAINER_CONFIG = {
  networkMode: 'none',
  readOnly: false,
  tmpfs: {
    '/tmp': 'rw,nosuid,size=10m',
    '/workspace': 'rw,nosuid,size=10m',
  },
  capDrop: ['ALL'],
  securityOpt: [
    'no-new-privileges',
  ],
  pidsLimit: parseInt(process.env.MAX_PIDS || '64', 10),
  ulimits: {
    nofile: { soft: 256, hard: 256 },
    nproc: { soft: 64, hard: 64 },
  },
};

export const EXECUTION_LIMITS = {
  maxCodeSize: 1024 * 100, // 100KB
  maxOutputSize: parseInt(process.env.MAX_OUTPUT_SIZE_KB || '1024', 10) * 1024,
  defaultTimeout: 10000, // 10 seconds
  maxMemoryMB: parseInt(process.env.MAX_MEMORY_MB || '128', 10),
  maxCpuCores: parseFloat(process.env.MAX_CPU_CORES || '1'),
};
